---
- name: Ensure /opt/k3s
  ansible.builtin.file:
    path: /opt/k3s
    state: directory
    owner: root
    group: root
    mode: "0750"
  become: true

- name: When performing an airgap install, ensure the image dir exists
  become: true
  when: k3s_airgap_install | bool
  ansible.builtin.file:
    path: /var/lib/rancher/k3s/agent/images/
    state: directory
    owner: root
    group: root
    mode: "0750"

# ToDo: validate all possible user input combinations here
- name: Download the install script (http/s fetch)
  when: "'http://' in k3s_install_script_url or 'https://' in k3s_install_script_url"
  ansible.builtin.get_url:
    url: "{{ k3s_install_script_url }}"
    dest: /opt/k3s/install.sh
    mode: "0755"
    owner: root
    group: root
  become: true

- name: Download the k3s binary (https/s fetch)
  when: "'http://' in k3s_binary_url or 'https://' in k3s_binary_url"
  ansible.builtin.get_url:
    url: "{{ k3s_binary_url }}"
    dest: /usr/local/bin/k3s
    mode: "0755"
    owner: root
    group: root
  become: true

- name: Download the k3s images (https/s fetch)
  when:
    - "'http://' in k3s_images_url or 'https://' in k3s_images_url"
    - k3s_airgap_install
  ansible.builtin.get_url:
    url: "{{ k3s_images_url }}"
    dest: "/var/lib/rancher/k3s/agent/images/{{ k3s_images_url | basename }}"
    mode: "0644"
    owner: root
    group: root
  become: true

- name: Copy over the install script (file:// k3s_install_script_url)
  when:
    - "'file://' in k3s_install_script_url"
    - k3s_airgap_install
  ansible.builtin.copy:
    src: "{{ k3s_install_script_url | regex_replace('^file://', '') }}"
    dest: /opt/k3s/install.sh
    mode: "0755"
    owner: root
    group: root
  become: true

- name: Copy over the k3s binary (file:// k3s_binary_url)
  when: "'file://' in k3s_binary_url"
  ansible.builtin.copy:
    src: "{{ k3s_binary_url | regex_replace('^file://', '') }}"
    dest: /usr/local/bin/k3s
    mode: "0755"
    owner: root
    group: root
  become: true

- name: Copy over the k3s images (file:// k3s_images_url)
  when: "'file://' in k3s_images_url"
  ansible.builtin.copy:
    src: "{{ k3s_images_url | regex_replace('^file://', '') }}"
    dest: "/var/lib/rancher/k3s/agent/images/{{ k3s_images_url | basename }}"
    mode: "0644"
    owner: root
    group: root
  become: true

- name: Ensure /etc/rancher/k3s
  ansible.builtin.file:
    path: /etc/rancher/k3s
    state: directory
    owner: root
    group: root
    mode: "0750"
  become: true

- name: Template in registries.yaml
  when: "k3s_registries_yaml | default(False) | bool"
  ansible.builtin.template:
    content: "{{ k3s_registries_yaml }}"
    dest: /etc/rancher/k3s/registries.yaml
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Check if k3s service exists and is running (control plane)
  ansible.builtin.set_fact:
    k3s_status: "{{ ansible_facts.services['k3s.service']['state'] | default('absent') }}"

- name: Check if k3s-agent service exists and is running (worker node)
  ansible.builtin.set_fact:
    k3s_status: "{{ ansible_facts.services['k3s-agent.service']['state'] | default('absent') }}"
  when: "k3s_status != 'running' and 'k3s-agent.service' in ansible_facts.services"

# ToDo: let users define their own, immutable join token
- name: If we're not in a cluster, perform the node registration tasks
  become: true
  when: k3s_status != 'running' or k3s_force_reinstall
  vars:
    cluster_bootstrap_flags: "{{ '--cluster-init' if k3s_bootstrap_node else '' }}"
    node_role: "{{ 'server' if k3s_control_plane_node or k3s_bootstrap_node else 'agent' }}"
    join_flags: "{{ '--server https://' + k3s_bootstrap_node_ip + ':6443 --token ' + k3s_join_token if not k3s_bootstrap_node else '' }}"
  ansible.builtin.command:
    cmd: >
      /opt/k3s/install.sh {{ node_role }}
      {{ join_flags }}
      {{ cluster_bootstrap_flags }}
  environment:
    INSTALL_K3S_SKIP_DOWNLOAD: "true"
