---
- name: Include pre-flight validation tasks
  ansible.builtin.include_tasks: pre_flight.yml

- name: Include k3s uninstall tasks
  ansible.builtin.include_tasks: k3s_uninstall.yml
  when: k3s_force_reinstall | bool or k3s_uninstall | bool

- name: Include k3s_install tasks
  ansible.builtin.include_tasks: k3s_install.yml
  when: not k3s_uninstall | bool

- name: Bootstrap Juno
  when: juno_install and k3s_control_plane_node
  ansible.builtin.include_tasks: juno_install.yml
