---
- name: Assert we are on support major version of Ubuntu
  ansible.builtin.assert:
    that:
      - ansible_distribution_major_version | string in supported_major_versions
    fail_msg: "This Ansible role is only supported on  22.x."
  vars:
    supported_major_versions:
      - "22"
      - "24"
