---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Make sure python3 is installed
      ansible.builtin.package:
        name: python3
        state: present
      become: true
    - name: If selinux is installed, make it permissive
      ansible.builtin.command:
        cmd: setenforce 0
      when: "'selinux' in ansible_facts.services"
      ignore_errors: true
      become: true
