name: Delete Branch on PR Close
on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    runs-on:
      - self-hosted
    steps:
      - name: delete branch
        if: ${{ !contains(fromJson('["juno-bootstrap", "genesis-deployment", "orion-deployment"]'), toLower(github.event.repository.name)) }}
        uses: SvanBoxel/delete-merged-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_PASS }}
