on:
  push:
    paths-ignore:
      - '.github/**'
      - "README.md"
      - "docs/**"
  workflow_dispatch:
  workflow_call:
jobs:
  molecule-test:
    runs-on:
      - X64
    strategy:
      max-parallel: 1 # this can be faster, working on it :)
      matrix:
        # In order to speed up the CI here we are only going to run the major versions we are going to support
        # instead of all versions, these should be tested locally when making relevant changes
        # Currently focus on, deb, rhel and arm support
        os-target: [ubuntu24, rocky101, arm-ubuntu24]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Run molecule tests
        env:
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          DISTRO: ${{ matrix.os-target }}
        run: |
          make test-${{ matrix.os-target }}
