on:
  create:

permissions:
  contents: write
  issues: write
  pull-requests: write
  repository-projects: read # github's current permission scheme makes this necessary: https://github.com/cli/cli/issues/6274

jobs:
  PR:
    runs-on: X64
    if: ${{ github.event.ref_type == 'branch' && !contains(fromJson('["Juno-Bootstrap", "Genesis-Deployment", "Orion-Deployment"]'), github.event.repository.name) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.JUNO_CI_APP_ID }}
          private-key: ${{ secrets.JUNO_CI_APP_PRIVATE_KEY }}
      - name: Checkout CI repository
        uses: actions/checkout@v4
        with:
          repository: juno-fx/ci
          ref: main
          path: .juno-ci
          token: ${{ secrets.RO_CI_REPO_TOKEN }}
      - name: Run PR on branch creation
        uses: ./.juno-ci/actions/workflow/pr-on-branch-creation
        with:
          gh_token: ${{ steps.generate-token.outputs.token }}
