name: PR Review Comment Message

on:
  pull_request_review_comment:
    types:
      - created
  pull_request_review:
    types:
      - submitted
jobs:
  google-chat-review-action:
    uses: juno-fx/ci/.github/workflows/ref-pr-review_comment-gChat-notification.yaml@main
    secrets: inherit